version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo_project_app
    ports:
      - "7001:80"
    volumes:
      - .:/var/www/demo-project
    networks:
      - demo-project

networks:
  demo-project:
    driver: bridge
